### ISSUE TITLE
Path blocks/tilling don't use durability & Sickles can till 

### ISSUE THREAD

**Issue by ArZorMC** [chrismin13/VanillaAdditions#6]
Custom shovel don't take any durability damage when making path blocks or tilling ground which they do in vanilla.
Ans as the title says it seems unintentional that sickles can also till dirt into farmland

**Comment by chrismin13** [comment]
These are both Additions API issues, and have been reported in the following links:
https://github.com/chrismin13/AdditionsAPI/issues/21
https://github.com/chrismin13/AdditionsAPI/issues/25
Thanks for taking the time to report the issue, I hope I can resolve it soon! This issue is closed, any future updates should be made on the two threads linked above.
